In [5]:
from keras.models import load_model
from keras.preprocessing import image
from keras.applications.vgg16 import preprocess_input
import numpy as np


In [19]:
model=load_model('model_vgg16.h5')
img= image.load_img(r'C:\Users\Chaitanya Kaul\chest_xray\val\NORMAL\NORMAL2-IM-1438-0001.jpeg',target_size=(224,224))

In [20]:
x= image.img_to_array(img)
x= np.expand_dims(x,axis=0)
img_data= preprocess_input(x)
classes= model.predict(img_data)

In [22]:
classes

array([[0., 1.]], dtype=float32)

In [24]:
model=load_model('model_vgg16.h5')
img= image.load_img(r'C:\Users\Chaitanya Kaul\chest_xray\val\NORMAL\NORMAL2-IM-1437-0001.jpeg',target_size=(224,224))

In [25]:
x= image.img_to_array(img)
x= np.expand_dims(x,axis=0)
img_data= preprocess_input(x)
classes= model.predict(img_data)

In [26]:
classes

array([[1., 0.]], dtype=float32)

In [27]:
model=load_model('model_vgg16.h5')
img= image.load_img(r'C:\Users\Chaitanya Kaul\chest_xray\val\PNEUMONIA\person1954_bacteria_4886.jpeg',target_size=(224,224))

In [28]:
x= image.img_to_array(img)
x= np.expand_dims(x,axis=0)
img_data= preprocess_input(x)
classes= model.predict(img_data)

In [29]:
classes

array([[1.000000e+00, 9.069357e-10]], dtype=float32)

In [30]:
model=load_model('model_vgg16.h5')
img= image.load_img(r'C:\Users\Chaitanya Kaul\chest_xray\val\PNEUMONIA\person1947_bacteria_4876.jpeg',target_size=(224,224))

In [31]:
x= image.img_to_array(img)
x= np.expand_dims(x,axis=0)
img_data= preprocess_input(x)
classes= model.predict(img_data)

In [32]:
classes

array([[0., 1.]], dtype=float32)